Repository UNO-Coders/Web-Development, pull requests merged in 2022-10, with the labels that each got.

#86 Added HTML Books for beginner from Tutorialspoint
  html_tutorial.pdf
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022, books

#87 Added Node.js Boilerplace Code
  Next.js Boilerplate/.eslintignore
  Next.js Boilerplate/.eslintrc
  Next.js Boilerplate/.gitignore
  Next.js Boilerplate/.husky/commit-msg
  Next.js Boilerplate/.husky/pre-commit
  Next.js Boilerplate/.vscode/extensions.json
  Next.js Boilerplate/.vscode/launch.json
  Next.js Boilerplate/.vscode/settings.json
  Next.js Boilerplate/.vscode/tasks.json
  Next.js Boilerplate/CHANGELOG.md
  Next.js Boilerplate/LICENSE
  Next.js Boilerplate/Next-js-Boilerplate-master.zip
  Next.js Boilerplate/README.md
  Next.js Boilerplate/__mocks__/next/router.ts
  Next.js Boilerplate/commitlint.config.js
  Next.js Boilerplate/cypress.config.js
  Next.js Boilerplate/cypress/e2e/SeoMetadata.cy.ts
  Next.js Boilerplate/cypress/e2e/navigation.cy.ts
  Next.js Boilerplate/cypress/fixtures/example.json
  Next.js Boilerplate/cypress/support/e2e.ts
  Next.js Boilerplate/cypress/tsconfig.json
  Next.js Boilerplate/jest.config.js
  Next.js Boilerplate/jest.setup.js
  Next.js Boilerplate/lint-staged.config.js
  Next.js Boilerplate/netlify.toml
  Next.js Boilerplate/next-env.d.ts
  Next.js Boilerplate/next.config.js
  Next.js Boilerplate/package-lock.json
  Next.js Boilerplate/package.json
  Next.js Boilerplate/postcss.config.js
  Next.js Boilerplate/public/apple-touch-icon.png
  Next.js Boilerplate/public/assets/images/nextjs-starter-banner.png
  Next.js Boilerplate/public/favicon-16x16.png
  Next.js Boilerplate/public/favicon-32x32.png
  Next.js Boilerplate/public/favicon.ico
  Next.js Boilerplate/src/layouts/Meta.test.tsx
  Next.js Boilerplate/src/layouts/Meta.tsx
  Next.js Boilerplate/src/pages.test/about.test.tsx
  Next.js Boilerplate/src/pages.test/index.test.tsx
  Next.js Boilerplate/src/pages/_app.tsx
  Next.js Boilerplate/src/pages/_document.tsx
  Next.js Boilerplate/src/pages/about.tsx
  Next.js Boilerplate/src/pages/index.tsx
  Next.js Boilerplate/src/styles/global.css
  Next.js Boilerplate/src/templates/Main.test.tsx
  Next.js Boilerplate/src/templates/Main.tsx
  Next.js Boilerplate/src/utils/AppConfig.ts
  Next.js Boilerplate/tailwind.config.js
  Next.js Boilerplate/tsconfig.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022, Next.js, Learning-Resources

#90 Added a file
  Voice-Operated-Calculator/index.html
  Voice-Operated-Calculator/logo.png
  Voice-Operated-Calculator/mic.png
  Voice-Operated-Calculator/responsivevoice.js
  Voice-Operated-Calculator/script.js
  Voice-Operated-Calculator/style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#93 Created a twitter Tweeting Bot
  NodeJS/14-TwitterBot/index.js
  NodeJS/14-TwitterBot/package-lock.json
  NodeJS/14-TwitterBot/package.json
  NodeJS/14-TwitterBot/twitterClient.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#95 Added To-Do-List
  To-do-list/README.md
  To-do-list/css/font-awesome.css
  To-do-list/css/style.css
  To-do-list/fonts/FontAwesome.otf
  To-do-list/fonts/fontawesome-webfont.eot
  To-do-list/fonts/fontawesome-webfont.svg
  To-do-list/fonts/fontawesome-webfont.ttf
  To-do-list/fonts/fontawesome-webfont.woff
  To-do-list/fonts/fontawesome-webfont.woff2
  To-do-list/img/bg.jpg
  To-do-list/img/bg.png
  To-do-list/img/bg1.jpg
  To-do-list/img/bg2.jpg
  To-do-list/img/images.jpg
  To-do-list/index.html
  To-do-list/js/app.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#94 Create HeapSort.java
  HeapSort.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022, Learning-Resources

#96 React Hooks app to calculate the BMI of a person
  BMI-Calculator using JS/.gitignore
  BMI-Calculator using JS/.prettierrc.js
  BMI-Calculator using JS/.travis.yml
  BMI-Calculator using JS/LICENSE
  BMI-Calculator using JS/README.md
  BMI-Calculator using JS/cypress.json
  BMI-Calculator using JS/cypress/.eslintrc.json
  BMI-Calculator using JS/cypress/integration/BmiForm.spec.js
  BMI-Calculator using JS/cypress/plugins/index.js
  BMI-Calculator using JS/cypress/support/commands.js
  BMI-Calculator using JS/cypress/support/index.js
  BMI-Calculator using JS/images/1.jpg
  BMI-Calculator using JS/jsconfig.json
  BMI-Calculator using JS/package-lock.json
  BMI-Calculator using JS/package.json
  BMI-Calculator using JS/public/icon.ico
  BMI-Calculator using JS/public/icon.png
  BMI-Calculator using JS/public/icon192.png
  BMI-Calculator using JS/public/icon512.png
  BMI-Calculator using JS/public/index.html
  BMI-Calculator using JS/public/robots.txt
  BMI-Calculator using JS/src/components/App/App.css
  BMI-Calculator using JS/src/components/App/App.jsx
  BMI-Calculator using JS/src/components/App/App.test.js
  BMI-Calculator using JS/src/components/Bar/Bar.jsx
  BMI-Calculator using JS/src/components/Bar/Bar.test.js
  BMI-Calculator using JS/src/components/BmiForm/BmiForm.jsx
  BMI-Calculator using JS/src/components/BmiForm/BmiForm.test.js
  BMI-Calculator using JS/src/components/Info/Info.jsx
  BMI-Calculator using JS/src/components/Info/Info.test.js
  BMI-Calculator using JS/src/helpers/localStorage.js
  BMI-Calculator using JS/src/index.css
  BMI-Calculator using JS/src/index.js
  BMI-Calculator using JS/src/setupTests.js
  BMI-Calculator using JS/yarn.lock
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022, Learning-Resources

#97 Tip Calculator using React-Redux
  Tip Calculator Using JS/.gitignore
  Tip Calculator Using JS/.prettierrc
  Tip Calculator Using JS/README.md
  Tip Calculator Using JS/package.json
  Tip Calculator Using JS/public/favicon.ico
  Tip Calculator Using JS/public/index.html
  Tip Calculator Using JS/public/logo192.png
  Tip Calculator Using JS/public/logo512.png
  Tip Calculator Using JS/public/manifest.json
  Tip Calculator Using JS/public/robots.txt
  Tip Calculator Using JS/src/components/Application.js
  Tip Calculator Using JS/src/components/Calculator.js
  Tip Calculator Using JS/src/components/MenuItem.js
  Tip Calculator Using JS/src/components/MenuItems.js
  Tip Calculator Using JS/src/components/NewItemForm.js
  Tip Calculator Using JS/src/components/Summary.js
  Tip Calculator Using JS/src/components/SummaryLine.js
  Tip Calculator Using JS/src/components/TipSelect.js
  Tip Calculator Using JS/src/containers/TipSelectContainer.js
  Tip Calculator Using JS/src/index.css
  Tip Calculator Using JS/src/index.js
  Tip Calculator Using JS/src/store/index.js
  Tip Calculator Using JS/src/store/items/actions.js
  Tip Calculator Using JS/src/store/items/reducer.js
  Tip Calculator Using JS/src/store/tip-percentage/actions.js
  Tip Calculator Using JS/src/store/tip-percentage/reducer.js
  Tip Calculator Using JS/src/utilities.js
  Tip Calculator Using JS/yarn.lock
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#98 random gradient hex color combination
  Hex Color Gradient using JS/colors.png
  Hex Color Gradient using JS/index.html
  Hex Color Gradient using JS/script.js
  Hex Color Gradient using JS/style.css
Labels: enhancement, help wanted, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#100 built minesweeper solver game - exercisim excercise
  rust-examples/minesweeper.rs
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#101 write luhn algo for credit/debit card number validator
  rust-examples/luhn.rs
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#103 implement logger in rust
  rust-examples/logger.rs
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#104 Added unique clock
  Unique-clock/1.png
  Unique-clock/2.png
  Unique-clock/3.png
  Unique-clock/4.png
  Unique-clock/index.css
  Unique-clock/index.html
  Unique-clock/index.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022, hacktoberfest2022

#107 added cli gui python application
  cli-gui/app.py
  cli-gui/requirements.txt
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#109 added setup steps for developers
  installation-docket/setup.md
Labels: enhancement, good first issue, help wanted, hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#108 added functional pipes utility
  functional-pipes/app.py
  functional-pipes/pipes/__init__.py
Labels: enhancement, hacktoberfest, hacktoberfest2020, hacktoberfest-accepted, hacktoberfest-2022, Learning-Resources

#110 Added tic tac toe game in C
  Tic-Tac-Toe/TTT.c
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, Learning-Resources

#111 ✅ added the Folder Youtube videos
  Youtube-Videos/index.html
Labels: documentation, enhancement, good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022, Learning-Resources

#113 matrix style in python
  Python_Examples/matrix.py
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022, hacktoberfest2022

#114 Update README.md
  README.md
Labels: documentation, enhancement, good first issue, Learning-Resources

#115 Added Glassmorphisim 3D Login and Signup Project
  Glassmorphisim 3D SignUp/login.css
  Glassmorphisim 3D SignUp/login.html
  Glassmorphisim 3D SignUp/temp.md
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#112 Added youtube videos
  Youtube-Videos/lanuages
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#116 ✅ Added the resources for android development
  Youtube-Videos/Android-Dev-Videos/resources.html
  Youtube-Videos/Machine-Learning-Videos/ML-resources.html
  Youtube-Videos/UI-UX-Videos/resources.html
  Youtube-Videos/Web-Dev-Videos/index.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022, Learning-Resources

#120 Added Resources for JS
  Youtube-Videos/Web-Dev-Videos/index.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#118 ✅ Added react videos for learning react resources
  Bootstrap Examples/Learning-resource/bootstrap-resource.html
  Reactjs-Resources/ReactJS_Resourses_List/react_resourses.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022, Learning-Resources

#123 Added POST request example
  gin-go API/go.mod
  gin-go API/go.sum
  gin-go API/main.go
  go-request/go.mod
  go-request/main.go
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#122 Random Hex Color Code Generator Chrome extension
  Random Hex Color Code/index.html
  Random Hex Color Code/logo.png
  Random Hex Color Code/manifest.json
  Random Hex Color Code/samples/Screenshot (1424).png
  Random Hex Color Code/samples/Screenshot (1425).png
  Random Hex Color Code/script.js
  Random Hex Color Code/style.css
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#125 Kruskal Algorithm
  Kruskal_algo.c
Labels: enhancement, good first issue, help wanted, hacktoberfest-accepted, hacktoberfest-2022, hacktoberfest2022

#126 Prime Number
  prime.c
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022, Learning-Resources

#129 e-commerce product page template
  ecom.css
  ecom.html
  ecom.js
  hi.txt
  image-avatar.png
  image-product-1-thumbnail.jpg
  image-product-1.jpg
  image-product-2-thumbnail.jpg
  image-product-2.jpg
  image-product-3-thumbnail.jpg
  image-product-3.jpg
  image-product-4-thumbnail.jpg
  image-product-4.jpg
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022, Learning-Resources

#132 Perfect Number
  Perfect_number.c
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022, Learning-Resources

#133 H1
  templates/index.html
  templates/style.css
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022, Learning-Resources

#135 Added Country Guide API Project
  Country Guide/ReadME.md
  Country Guide/index.html
  Country Guide/style.css
  Country Guide/style.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022, Learning-Resources
