Repository UNO-Coders/Web-Development, pull requests merged in 2023-10, with the labels that each got.

#140 FastAPI Starter
  .gitignore
  FastApi/Readme.md
  FastApi/server.py
  FastApi/src/__init__.py
  FastApi/src/controllers/__init__.py
  FastApi/src/controllers/route.py
  Python_Examples/utilities.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#141 Interview Prep Directory
  Interview Prepration/GOC/Material.md
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#144 Python Multi Threading
  Python Multithreading/Readme.md
  Python Multithreading/threadutility.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#148 Amdocs Devops Enginneer Interview experience
  Amdocs/Devops Engineer/README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted, hacktoberfest2023, Interview Prepration

#147 login page added.
  LoginPage/Index.html
  LoginPage/Motivational Desktop Wallpaper (3).png
  LoginPage/bxs-log-in-circle.svg
  LoginPage/istockphoto-1407633532-1024x1024.jpg
  LoginPage/istockphoto-1437809296-1024x10241.jpg
  LoginPage/log-in-6398177_1280.png
  LoginPage/style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#154 added Mouse Hover Animations
  MouseHoverAnimation/MouseHoverGlow.css
  MouseHoverAnimation/MouseHoverGlow.html
  MouseHoverAnimation/mouseHoverGlow.gif
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#158 added AvatarGenerator
  AvatarGenerator/avatar.css
  AvatarGenerator/avatar.html
  AvatarGenerator/avatar.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#157 added Wack-a-mole-game
  Wack-a-mole-game/README.md
  Wack-a-mole-game/dirt.png
  Wack-a-mole-game/index.html
  Wack-a-mole-game/mole.jpg
  Wack-a-mole-game/mole.png
  Wack-a-mole-game/script.js
  Wack-a-mole-game/styles.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#151 Updated/webdev resources for 2023
  Youtube-Videos/UI-UX-Videos/resources.html
  Youtube-Videos/Web-Dev-Videos/index.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#159 BalloonPoppingGame
  BalloonPoppingGame/README.md
  BalloonPoppingGame/app.js
  BalloonPoppingGame/index.html
  BalloonPoppingGame/javascript balloon popping project.png
  BalloonPoppingGame/style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#160 Added a Advance Online Calculator with good Response and user friendly interface.
  Calculator/index.html
  Calculator/index.js
  Calculator/style.css
  JsCalculator/JSCalculator.css
  JsCalculator/JSCalculator.html
  JsCalculator/JSCalculator.js
  JsCalculator/pic1.jpg
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#161 Updated/webdev resources
  Youtube-Videos/Android-Dev-Videos/resources.html
  Youtube-Videos/Machine-Learning-Videos/ML-resources.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#163 add Currency Converter
  CurrencyConverter/README.md
  CurrencyConverter/index.html
  CurrencyConverter/script.js
  CurrencyConverter/ss.png
  CurrencyConverter/style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#164 add Correct Number Guess Game
  Correct Number Guess Game/Game.class
  Correct Number Guess Game/Game.java
  Correct Number Guess Game/Game1.class
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#168 Added React.js Interview Prepration Links
  Interview Prepration/frontend/Reactjs.md
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023, Interview Prepration

#169 Added JS Interview Prepration Links
  Interview Prepration/frontend/Javascript.md
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023, Interview Prepration

#170 Added Python Interview Prepration Links
  Interview Prepration/Python/begineer.md
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023, Interview Prepration

#167 feat : added javascript app note keeper
  Note-keeper-App JS/Fav/android-chrome-192x192.png
  Note-keeper-App JS/Fav/android-chrome-512x512.png
  Note-keeper-App JS/Fav/apple-touch-icon.png
  Note-keeper-App JS/Fav/browserconfig.xml
  Note-keeper-App JS/Fav/favicon-16x16.png
  Note-keeper-App JS/Fav/favicon-32x32.png
  Note-keeper-App JS/Fav/favicon.ico
  Note-keeper-App JS/Fav/frame.png
  Note-keeper-App JS/Fav/mstile-150x150.png
  Note-keeper-App JS/Fav/site.webmanifest
  Note-keeper-App JS/README.md
  Note-keeper-App JS/index.html
  Note-keeper-App JS/script.js
  Note-keeper-App JS/style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#166 added a GUI tic tac toe python program made using tkinter in which we have options to play with the computer and with the another player as well
  Python_Examples/tic tac toe.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#171 Added Java Interview Prepration Links
  Interview Prepration/Java/java.md
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023, Interview Prepration
